### PR TITLE
Add Travis CI config

### PR DESCRIPTION
**Pull request by andyjcboyle**
Hey .. as per previous conversation I've added config which I believe should work on Travis CI ... but you'll need to setup Travis CI itself - https://travis-ci.org/ & https://docs.travis-ci.com/user/getting-started/

For my own project I went through this and worked okay, the only real difference being this one needed a (very) simple script to wrap the sbt commands as the projects are not top level.

My project for reference is:-

gthub : https://github.com/andysudo/scram
travis : https://travis-ci.org/andysudo/scram

You need admin rights to the project in order to setup so I haven't been able to test this specifically on travis.

### CODE REVIEW

**Comment by andyjcboyle** [comment]
meant to also say the sbt commands just do a "sbt test" essentially ... but just to test everything works with travis. I suspect you'd want to change to also deploy ( to OSS Sonatype )

**Comment by lewismj** [comment]
Hi, sorry for the delay, bit busy in work!, I'll try to merge in the PR  now...

**Comment by lewismj** [comment]
Thanks very much for looking at that.

**Comment by lewismj** [comment]
Hi,

I merged in the PR, hopefully over the weekend, I will get chance
to look at setting up my travis - I'll ask in my office as there
are a few people that have used it previously.

Regards,
Mike

**Comment by andyjcboyle** [comment]
Cool nps, was more of a hank you for your earlier work :-) If you need any help can let me know.

**Pull request merged**
